### PR TITLE
Check for `aes` params in `uses_geom_param()`

### LINKED ISSUE #23: Get and check aes params
It would be useful to be able to check for aesthetic parameters (i.e., aesthetics that have been set and not mapped), such as `fill = "blue"`:

``` r
library(ggcheck)
library(ggplot2)

p <-
  ggplot(mpg, aes(manufacturer)) +
  geom_bar(fill = "blue", width = 0.5)
```

<sup>Created on 2021-11-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

`uses_geom_param()` checks "geom params", (`binwidth`, etc.), but not "aes params" (`fill = "blue"`):

``` r
uses_geom_param(p, "bar", params = list(fill = "blue"))
#> Error in uses_geom_param(p, "bar", params = list(fill = "blue")): Grading error: the supplied parameters 'fill' are invalid.
uses_geom_param(p, "bar", params = list(width = 0.5))
#> [1] TRUE
```

It would also be nice to be able to easily get aes params. You can do:

``` r
get_geom_layer(p, geom = "bar")$layer$aes_params
#> $fill
#> [1] "blue"
```

but it would be nice to have a function.

### PR DESCRIPTION
**Pull request by rossellhayes**
- Renames `uses_geom_param()` → `uses_geom_params()`, since it can check multiple params.
	- `uses_geom_param()` is preserved as an alias for backwards compatibility.
- Adds support for checking `aes` layer parameters with `uses_geom_params()`. You can now check for `geom`, `stat`, and `aes` layer parameters. 
- `params` can now be set by passing named arguments to `...`.
- `uses_geom_params()` now returns a named logical vector.
- Attempting to check an unset or invalid parameter now returns `FALSE` instead of an error.

``` r
library(ggcheck)
library(ggplot2)

p <- ggplot(mpg, aes(manufacturer)) +
  geom_bar(fill = "blue", color = "red", width = 0.5)

uses_geom_params(p, "bar", params = list(width = 0.5))
#> width 
#>  TRUE
uses_geom_params(p, "bar", params = list(fill = "blue"))
#> fill 
#> TRUE

uses_geom_params(p, "bar", width = 0.5, fill = "blue")
#> width  fill 
#>  TRUE  TRUE

# Unnamed arguments check if parameter is set
uses_geom_params(p, "bar", "fill", "color", "linetype")
#>     fill    color linetype 
#>     TRUE     TRUE    FALSE

# Support for color and colour
uses_geom_params(p, "bar", color = "red")
#> color 
#>  TRUE
uses_geom_params(p, "bar", colour = "red")
#> colour 
#>   TRUE

# Unset params return FALSE
uses_geom_params(p, "bar", linetype = "dashed")
#> linetype 
#>    FALSE
uses_geom_params(p, "bar", typo = TRUE)
#>  typo 
#> FALSE

# Alias for backwards compatibility
uses_geom_param(p, "bar", fill = "blue")
#> fill 
#> TRUE
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Closes #23 and #31.

### CODE REVIEW

File: R/geoms.R [hunk 1]
```diff
@@ -102,39 +102,52 @@ uses_geoms <- function(p, geoms, stats = NULL, exact = TRUE) {
   }
 }
 
-#' Does a layer use a specific geom parameter?
+#' Does a layer use a specific parameter?
```
Comment (skaltman) [inline R/geoms.R:105]: Since you can check multiple parameters, maybe this should be:

```suggestion
#' Does a layer use one or more specific parameters?
```

Comment (skaltman) [reply R/geoms.R:105]: Actually, with that in mind, maybe the function should be `uses_geom_params()`?

**Review by skaltman — APPROVED** [review]
This looks great! One thing I noticed:

* You have to specify color with a "u." Could we allow "color" like [`uses_aesthetics()` does](https://github.com/rstudio/ggcheck/blob/806cfe95549e6f84e0b3c57514aa3b00ecb44a07/R/mappings.R#L194)?

**Comment by skaltman** [comment]
Also, I think it may complicate some grading code that this returns an error:

``` r
p <- 
  ggplot(mpg, aes(manufacturer)) +
  geom_bar(width = 0.5)

uses_geom_param(p, "bar", width = 0.5, fill = "blue")
#> Error in uses_geom_param(p, "bar", width = 0.5, fill = "blue"): Grading error: the supplied parameters 'fill' are invalid.
```

I'm not sure what it should return, but I think I'd want to be able to check if someone has used an argument at all.

**Comment by rossellhayes** [comment]
@skaltman 
> I'm not sure what it should return, but I think I'd want to be able to check if someone has used an argument at all.

Should it just return `FALSE` for parameters that are unset?

File: R/geoms.R (hunk 1 above)
Comment (rossellhayes) [reply R/geoms.R]: Great points, I've updated to make this change.

**Comment by skaltman** [comment]
> Should it just return `FALSE` for parameters that are unset?

I think it would be useful to tell the difference between code that sets a parameter incorrectly and code that doesn't set it at all. 

Does it make sense to handle this like `uses_labels()` does? For example:

```
p <-
  ggplot(mpg, aes(manufacturer)) +
  geom_bar(fill = "blue") 
```

```
uses_geom_param(p, geom = "bar", "fill")
```

returns `TRUE`, but

```
uses_geom_param(p, geom = "bar", fill = "red")
```

returns `FALSE`?

**Comment by rossellhayes** [comment]
@skaltman I'll get to work on that. One thing to note is that while unset aes parameters don't exist, an unset geom or stat parameter could have a default value, so this would only really work for `aes` parameters.

``` r
library(ggplot2)

p <- ggplot() + geom_bar()

p$layers[[1]]$aes_params
#> named list()
p$layers[[1]]$geom_params
#> $width
#> NULL
#> 
#> $na.rm
#> [1] FALSE
#> 
#> $orientation
#> [1] NA
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gadenbuie** [comment]
> an unset geom or stat parameter could have a default value

Can we follow the pattern we initiated with `default_label()`? [`geom_defaults()`](https://github.com/tidyverse/ggplot2/blob/main/R/geom-defaults.r) _might_ be helpful here (or maybe it's just for _setting_ defaults and doesn't help determine the geom's current default).

**Comment by gadenbuie** [comment]
Oh wait, the plot actually carries around the default aes values for the geom

``` r
library(ggplot2)

p <-
  ggplot(mpg, aes(manufacturer)) +
  geom_bar(fill = "blue") 

p$layers[[1]]$geom$default_aes
#> Aesthetic mapping: 
#> * `colour`   -> NA
#> * `fill`     -> "grey35"
#> * `size`     -> 0.5
#> * `linetype` -> 1
#> * `alpha`    -> NA
```

**Comment by gadenbuie** [comment]
Oh wait again, I see I'm thinking about this backwards: we can't tell between unset and default `$geom_params`, such as `na.rm = FALSE`. I think the behavior of following `uses_labels()` but possibly without trying to determine if a geom or stat param is default is totally fine

**Comment by rossellhayes** [comment]
Yeah, aes params aren't a problem, because default values and set values are stored differently. But geom params always have a value, so it's impossible for us to tell whether a user set e.g. `na.rm = FALSE`, or whether that just came as the default. Do you think it's necessary to implement a `default_param()` function like we have for `default_label()`?

**Comment by gadenbuie** [comment]
> Do you think it's necessary to implement a `default_param()` function like we have for `default_label()`?

It seems like it might be possible to determine the default geom param values from the `Geom` ggproto object, but I also think we can tackle that in a separate issue/PR.

**Comment by rossellhayes** [comment]
I incorporated a solution to #31 in this PR to fix an outstanding issue. Named arguments to `uses_geom_params()` can now detect if a parameter has a default value.

``` r
library(ggcheck)
library(ggplot2)

p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_smooth()

# The user has not set `level`
uses_geom_params(p, "smooth", "level")
#> level 
#> FALSE

# But 0.95 is the default value
uses_geom_params(p, "smooth", level = 0.95)
#> level 
#>  TRUE

default_params(p, "smooth", "level")
#> $level
#> [1] 0.95
```

<sup>Created on 2021-12-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

File: R/geom_params.R [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+#' @examples
+#' require(ggplot2)
+#'
+#' p <- ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
+#'   geom_smooth(aes(color = class))
+#'
+#' # Returns the parameters the ggplot would use by default for a layer
+#' default_params(p, "smooth", "linetype")
+#' default_params(p, "smooth", "se", "level")
+#' default_params(p, "smooth")
```
Comment (gadenbuie) [inline R/geom_params.R:112]: `default_params()` vs `default_label()` doesn't feel consistent and it'd be good to articulate why the difference exists or what benefit we derive out of the inconsistent naming that makes it worth it.

I also like `capture_dots()` but I'm starting to feel like it's bordering on an anti-pattern. I think I'd prefer

```
default_params(p, "smooth", c("se", "level"))
```

instead, where there are clearly three arguments, each of which can be named.

File: R/utils.R [hunk 3]
```diff
@@ -334,3 +334,9 @@ map_stat <- function(stat) {
     stat = stat_lookup$STAT[which(stat_lookup$stat == stat)]
   )
 }
+
+capture_dots <- function(...) {
```
Comment (gadenbuie) [inline R/utils.R:338]: Since `capture_dots()` doesn't really do any quasiquotation or metaprogramming, I think we should call this helper `flatten_dots()`.

File: R/geom_params.R [hunk 4]
```diff
@@ -0,0 +1,187 @@
...
+#'   Unnamed arguments will check whether any value was set for that parameter.
+#'   Named arguments will check whether the parameter with the same name has a
+#'   matching value.
+#'   Each argument should have a name matching a [ggplot][ggplot2::ggplot]
+#'   layer parameter.
+#'   Values may be passed as arguments or as list elements.
+#' @param params A named list of geom or stat parameter values, e.g.
+#'   \code{list(outlier.alpha = 0.01)}.
+#'   This list is combined with any inputs to `...`
+#' @param i A numerical index, e.g. \code{1}.
```
[the remark this answers is not in the document]
Comment (gadenbuie) [reply R/geom_params.R:37]: Reading through the changes a little more I realized we've had the `i` argument for a little while. Let's leave this as is for now but register that we might want to change the interface in the near future.

File: R/geom_params.R [hunk 5]
```diff
@@ -0,0 +1,187 @@
...
+#' aes parameter. For example, in \code{geom_histogram(binwidth = 500)}, the
+#' \code{binwidth} is a stat parameter, while in
+#' \code{geom_histogram(fill = "blue")}, the \code{fill} is an aes parameter.
+#' \code{uses_geom_params} will take this into account and check geom, stat, and
+#' aes parameters.
+#'
+#' Note that `uses_geom_params()` can detect aes _parameters_, but not aes
+#' _mappings_. Parameters are set directly within a layer (e.g.
+#' `geom_point(color = "blue")`), while mappings are set using
+#' [`aes()`][ggplot2::aes] (e.g. `geom_point(aes(color = class))`).
```
Comment (gadenbuie) [inline R/geom_params.R:21]:
```suggestion
#' _mappings_. Parameters are set to static values directly within a layer (e.g.
#' `geom_point(color = "blue")`), while mappings associate variables in the data with plot aesthetics using
#' [`aes()`][ggplot2::aes] (e.g. `geom_point(aes(color = class))`).
```

**Review by gadenbuie — APPROVED** [review]

File: R/geom_params.R [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+#'   \code{list(outlier.alpha = 0.01)}.
+#'   This list is combined with any inputs to `...`
+#' @param i A numerical index, e.g. \code{1}.
+#'
+#' @return A named logical vector of the same length as the number of inputs
+#'   to `...`.
+#' @family functions for checking geom parameters
+#' @export
+#'
+#' @examples
```
Comment (gadenbuie) [inline R/geom_params.R:44]: Can we move `@examples` above the `@param`s please?

File: R/geom_params.R (hunk 2 above)
Comment (rossellhayes) [reply R/geom_params.R]: Resolved in 670a993 (`params` instead of `...`) and f2b5d3f (renaming functions)

File: R/utils.R (hunk 3 above)
Comment (rossellhayes) [reply R/utils.R]: Resolved in 57ae862

File: R/geom_params.R (hunk 6 above)
Comment (rossellhayes) [reply R/geom_params.R]: Resolved in 3cf709f
